name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  compile:
    uses: ./.github/workflows/jobs/compile.yml

  unit-tests:
    needs: compile
    uses: ./.github/workflows/jobs/unit-tests.yml

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/jobs/integration-tests.yml
