name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  unit-tests:
    needs: compile
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/integration-tests.yml

  snyk:
    needs: integration-tests
    uses: ./.github/workflows/snyk.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
